/* L2 ONE · Caixa diário. Os registros sincronizam pela API; não são saldos bancários. */
const cashBRL=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const cashAmount=v=>parseBRLCents(v)/100;
function cashRows(day){return (s.cashEntries||[]).filter(x=>x.date===day).sort((a,b)=>String(a.createdAt||'').localeCompare(String(b.createdAt||'')))}
function cashBalance(day){const d=(s.cashDays||[]).find(x=>x.date===day);return d?Number(d.opening||0)+cashRows(day).reduce((n,x)=>n+(x.type==='Entrada'?Number(x.amount): -Number(x.amount)),0):null}
function renderCash(){
 if(!financeAllowed())return '<div class="box">Acesso restrito ao financeiro.</div>';
 const day=window.cashSelectedDay||today(),d=(s.cashDays||[]).find(x=>x.date===day),rows=cashRows(day),balance=cashBalance(day);
 const total=t=>rows.filter(x=>x.type===t).reduce((n,x)=>n+Number(x.amount||0),0);
 const closed=d?.status==='Fechado';
 const dayOptions=(s.cashDays||[]).filter(x=>x.date<day).sort((a,b)=>b.date.localeCompare(a.date));
 const prev=dayOptions[0],suggested=prev?.status==='Fechado'?cashBalance(prev.date):null;
 return '<div class="page-heading"><div><span class="eyebrow">L2 Representações · Financeiro</span><h2>Caixa diário</h2><p>Controle por data, com abertura, movimentações e fechamento.</p></div></div>'+
 '<div class="box"><label>Data do caixa<input id="cashDate" type="date" value="'+esc(day)+'"></label><p class="muted">Abertura e fechamento são registros administrativos; confira o saldo com o extrato antes de fechar.</p></div>'+
 (!d?'<div class="box"><h3>Abrir caixa</h3><form id="cashOpen"><div class="row"><label>Saldo inicial (R$)<input name="opening" type="text" inputmode="decimal" placeholder="4.000,00" required value="'+(suggested===null?'':formatBRLInput(suggested))+'"></label><label>Observações<input name="notes" maxlength="500"></label></div><button>Abrir caixa</button></form></div>':
 '<div class="cards"><div class="card">Saldo inicial<strong>'+cashBRL(d.opening)+'</strong></div><div class="card">Entradas<strong>'+cashBRL(total('Entrada'))+'</strong></div><div class="card">Saídas<strong>'+cashBRL(total('Saída'))+'</strong></div><div class="card">Saldo calculado<strong>'+cashBRL(balance)+'</strong></div></div>'+
 '<div class="box"><h3>Caixa '+(closed?'fechado':'aberto')+'</h3><p>Responsável pela abertura: '+esc(d.openedBy||'—')+' · '+esc(d.openedAt||'')+'</p>'+(closed?'<p>Fechado por '+esc(d.closedBy||'—')+' em '+esc(d.closedAt||'')+' · saldo informado: '+cashBRL(d.closing)+'</p>':'<form id="cashClose"><label>Saldo conferido no fechamento (R$)<input name="closing" type="text" inputmode="decimal" placeholder="4.000,00" required value="'+formatBRLInput(balance)+'"></label><label>Observações de conferência<input name="notes" maxlength="500"></label><button>Fechar caixa</button></form>')+'</div>'+
 (!closed?'<div class="box"><h3>Novo lançamento</h3><form id="cashEntry"><div class="row"><label>Tipo<select name="type"><option>Entrada</option><option>Saída</option></select></label><label>Categoria<input name="category" required maxlength="100"></label><label>Descrição<input name="description" required maxlength="500"></label><label>Marca / Indústria<input name="brand" maxlength="120"></label><label>Valor (R$)<input name="amount" type="text" inputmode="decimal" placeholder="4.000,00" required></label><label>Comprovante / observação<input name="notes" maxlength="500" placeholder="Referência do comprovante"></label></div><button>Registrar movimento</button></form></div>':'')+
 '<div class="box"><h3>Movimentações do dia</h3><div class="scroll"><table><thead><tr><th>Tipo</th><th>Categoria</th><th>Descrição</th><th>Marca</th><th>Valor</th><th>Comprovante / observação</th></tr></thead><tbody>'+ (rows.map(x=>'<tr><td>'+esc(x.type)+'</td><td>'+esc(x.category)+'</td><td>'+esc(x.description)+'</td><td>'+esc(x.brand||'')+'</td><td>'+cashBRL(x.amount)+'</td><td>'+esc(x.notes||'')+'</td></tr>').join('')||'<tr><td colspan="6">Sem lançamentos nesta data.</td></tr>')+'</tbody></table></div></div>');
}
function cashBind(){
 const date=$('cashDate');if(date)date.onchange=()=>{window.cashSelectedDay=date.value;render()};
 const open=$('cashOpen');if(open)open.onsubmit=e=>{e.preventDefault();const day=window.cashSelectedDay||today(),amount=cashAmount(open.elements.opening.value);if(!Number.isFinite(amount)||amount<0||s.cashDays.some(x=>x.date===day))return alert('Abertura inválida ou caixa já existente.');const record={id:uid(),date:day,opening:amount,status:'Aberto',notes:open.elements.notes.value,openedAt:new Date().toISOString(),openedBy:s.user};s.cashDays.push(record);queue('cash_day',record);render()};
 const entry=$('cashEntry');if(entry)entry.onsubmit=e=>{e.preventDefault();const day=window.cashSelectedDay||today(),d=s.cashDays.find(x=>x.date===day),amount=cashAmount(entry.elements.amount.value);if(!d||d.status!=='Aberto'||!Number.isFinite(amount)||amount<=0)return alert('Abra o caixa e informe um valor positivo.');const record={id:uid(),date:day,type:entry.elements.type.value,category:entry.elements.category.value.trim(),description:entry.elements.description.value.trim(),brand:entry.elements.brand.value.trim(),amount,notes:entry.elements.notes.value.trim(),createdAt:new Date().toISOString(),createdBy:s.user};if(!record.category||!record.description)return alert('Categoria e descrição obrigatórias.');s.cashEntries.push(record);queue('cash_entry',record);render()};
 const close=$('cashClose');if(close)close.onsubmit=e=>{e.preventDefault();const day=window.cashSelectedDay||today(),d=s.cashDays.find(x=>x.date===day),amount=cashAmount(close.elements.closing.value);if(!d||d.status!=='Aberto'||!Number.isFinite(amount)||amount<0)return alert('Fechamento inválido.');if(!confirm('Confirma o fechamento do caixa? Após fechar, os lançamentos desta data ficam bloqueados.'))return;const record={...d,status:'Fechado',closing:amount,closingDifference:Math.round((amount-cashBalance(day))*100)/100,closingNotes:close.elements.notes.value,closedAt:new Date().toISOString(),closedBy:s.user};s.cashDays=s.cashDays.map(x=>x.id===d.id?record:x);queue('cash_day',record);render()};
}
