/* Private commercial drafts: immediate device save and serial cloud replication. */
(function(root){
 let pending=new Map(),running=false,timer;
 const storageKey=()=> 'l2one_drafts_v1:'+location.origin+':'+s.user;
 const read=()=>{try{return JSON.parse(localStorage.getItem(storageKey())||'{}')}catch(_){return {}}};
 function key(form){if(form.getAttribute('id')==='orderForm')return 'order:'+(window.currentOrder?.id||window.currentOrder?.draftKey||'new');if(form.getAttribute('id')==='visitForm')return 'visit:'+(form.elements.id?.value||'new');if(form.getAttribute('onsubmit')?.includes('saveCRMInteraction'))return 'interaction:'+(form.elements.clientId?.value||'new');return ''}
 function badge(form,text){let el=form.querySelector('[data-draft-status]');if(!el){el=document.createElement('p');el.dataset.draftStatus='';el.setAttribute('role','status');form.append(el)}el.textContent=text}
 function storeDraft(k,payload){const rows=read(),entry={key:k,payload,updatedAt:Date.now()};rows[k]=entry;localStorage.setItem(storageKey(),JSON.stringify(rows));pending.set(k,{entry,user:s.user,token:s.token});return entry}
 function capture(form){if(!form.isConnected)return;const k=key(form);if(!k)return;const fields={};for(const input of form.elements){if(!input.name||['file','password','submit','button'].includes(input.type))continue;fields[input.name]=input.type==='checkbox'?input.checked:input.value}const order=form.getAttribute('id')==='orderForm'?structuredClone(orderDraft()):null;if(order){for(const name of ['sellerResponsible','status','paymentTerms','notes','bellaBonusPercent','bellaBonusApproval'])if(name in fields)order[name]=fields[name];window.currentOrder=order}try{storeDraft(k,{fields,order});badge(form,'Rascunho salvo neste aparelho · envie à nuvem pelo botão Sincronizar.')}catch(_){badge(form,'Falha ao salvar rascunho: confira o espaço deste aparelho. Salve o registro antes de sair.')}}
 async function flush(){for(const entry of Object.values(read()))if(!pending.has(entry.key))pending.set(entry.key,{entry,user:s.user,token:s.token});if(running||!s.token||!navigator.onLine)return;running=true;try{for(const [k,item] of pending){if(item.user!==s.user||item.token!==s.token){pending.delete(k);continue}try{const r=await fetch(s.server+'/api/commercial/drafts',{method:'PUT',headers:{Authorization:'Bearer '+item.token,'Content-Type':'application/json'},body:JSON.stringify(item.entry)});if(!r.ok)break;if(pending.get(k)===item)pending.delete(k);const form=[...document.forms].find(f=>key(f)===k);if(form&&!pending.has(k))badge(form,'Rascunho salvo neste aparelho e na nuvem.')}catch(_){break}}}finally{running=false}}
 function persistOrder(){if(window.currentOrder)storeDraft('order:'+(window.currentOrder.id||window.currentOrder.draftKey||'new'),{order:structuredClone(window.currentOrder),fields:{}})}
 function startNewOrder(){const current=window.currentOrder||read()['order:new']?.payload?.order;if(current&&(current.clientId||Object.values(current.quantities||{}).some(Number)||current.notes)){const id=current.id||current.draftKey||('local-'+(crypto.randomUUID?.()||uid()));storeDraft('order:'+id,{order:{...current,draftKey:current.id?undefined:id},fields:{}})}clear('order:new')}
 function restoreOrder(){if(window.currentOrder)return;const entry=read()['order:new'];if(entry?.payload?.order&&(!entry.payload.order.clientId||s.clients.some(c=>c.id===entry.payload.order.clientId)))window.currentOrder=structuredClone(entry.payload.order)}
 function bind(){for(const form of document.forms){const k=key(form);if(!k)continue;const entry=read()[k];if(entry?.payload?.fields){for(const [name,value] of Object.entries(entry.payload.fields)){const field=form.elements[name];if(!field||['file','password'].includes(field.type)||(form.getAttribute('id')==='orderForm'&&['date','clientId','priceTable'].includes(name)))continue;if(field.type==='checkbox')field.checked=!!value;else if(!field.disabled)field.value=value}badge(form,'Rascunho recuperado · arquivos devem ser selecionados novamente.')}if(!form.dataset.draftBound){form.dataset.draftBound='1';form.addEventListener('input',()=>capture(form));form.addEventListener('change',()=>capture(form))}}}
 function clear(k){try{storeDraft(k,null)}catch(_){}}
 function list(){const rows=Object.values(read()).filter(x=>x.key.startsWith('order:')&&x.payload?.order&&(x.payload.order.clientId||x.payload.order.notes||Object.values(x.payload.order.quantities||{}).some(Number)));return rows.length?'<details class="box"><summary>Rascunhos de pedidos salvos · '+rows.length+'</summary>'+rows.map(x=>'<p>'+esc(client(x.payload.order.clientId).name||'Sem cliente')+' · '+esc(x.payload.order.date||'')+' <button type="button" onclick="CommercialDrafts.open(\''+esc(x.key)+'\')">Retomar rascunho</button></p>').join('')+'</details>':''}
 function open(k){const entry=read()[k];if(!entry?.payload?.order)return;window.currentOrder=structuredClone(entry.payload.order);if(!window.currentOrder.id&&k!=='order:new')window.currentOrder.draftKey=k.slice(6);show('pedidos')}
 async function load(){if(!s.token||!navigator.onLine)return;const token=s.token,user=s.user;try{const r=await fetch(s.server+'/api/commercial/drafts',{headers:{Authorization:'Bearer '+token}});if(!r.ok)return;const remote=await r.json();if(token!==s.token||user!==s.user||!Array.isArray(remote))return;const rows=read();for(const entry of remote)if(!rows[entry.key]||entry.updatedAt>rows[entry.key].updatedAt)rows[entry.key]=entry;localStorage.setItem(storageKey(),JSON.stringify(rows));for(const entry of Object.values(rows))pending.set(entry.key,{entry,user,token});if(!editingForm()){window.currentOrder=null;}}catch(_){}}
 document.addEventListener('visibilitychange',()=>{if(document.hidden){for(const f of document.forms)if(key(f))capture(f)}});window.addEventListener('pagehide',()=>{for(const f of document.forms)if(key(f))capture(f)});
 root.CommercialDrafts={flush,capture,bind,restoreOrder,clear,load,persistOrder,startNewOrder,list,open};
})(window);
