/* L2 ONE · Financeiro 360. Fonte única de realizados: lançamentos financeiros liquidados. */
const finCents=n=>Math.round(Number(n||0)*100);
const finSum=rows=>rows.reduce((sum,x)=>sum+finCents(x.Valor),0)/100;
const finDate=r=>String(r['Liquidação']||r.Data||'');
const finMonth=r=>String(r['Competência']||r.Data||'').slice(0,7);
const finOpen=r=>r['Situação']!=='Pago/Recebido';
function financeFilter(name,value){window.financeViewFilters=Object.assign({},window.financeViewFilters||{},{[name]:value});show('finance')}
function financeScope(){const filters=window.financeViewFilters||{},month=filters.month||today().slice(0,7);const matches=x=>(!filters.brand||x['Marca/Indústria']===filters.brand||x.brand===filters.brand)&&(!filters.owner||x['Responsável']===filters.owner||x.owner===filters.owner)&&(!filters.client||x.clientId===filters.client)&&(!filters.center||x['Centro de custo']===filters.center);return{filters,month,matches}}
function financeProjection(){const {month,matches}=financeScope();return (s.opportunities||[]).filter(x=>['Ganho','Pedido confirmado'].includes(x.stage)&&String(x.closeDate||x.wonAt||'').slice(0,7)===month&&matches(x)).filter(x=>!s.settlements.some(t=>t.clientId===x.clientId&&commissionKey(t.brand)===commissionKey(x.brand)&&String(t.billedDate||'').slice(0,7)===month)).map(x=>{const rate=s.commissionRates.find(c=>c.id===commissionKey(x.brand))?.rate;return{...x,rate,estimated:rate===undefined?null:Math.round(finCents(x.amount)*Number(rate)/100)/100}})}
function financeSeries(entries,month){const [year,m]=month.split('-').map(Number);return Array.from({length:6},(_,i)=>{const d=new Date(year,m-1+i-3,1),key=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;return{key,actual:finSum(entries.filter(x=>x.Tipo==='Receita'&&!finOpen(x)&&finDate(x).startsWith(key))),forecast:finSum(entries.filter(x=>x.Tipo==='Receita'&&finOpen(x)&&String(x.Vencimento||'').startsWith(key))),out:finSum(entries.filter(x=>x.Tipo==='Despesa'&&!finOpen(x)&&finDate(x).startsWith(key)))}})}
function financeChart(points){const ceiling=Math.max(1,...points.flatMap(x=>[x.actual,x.forecast,x.out])),x=i=>42+i*105,y=n=>156-Math.round(n/ceiling*115),actual=points.map((p,i)=>`${x(i)},${y(p.actual)}`).join(' '),forecast=points.map((p,i)=>`${x(i)},${y(p.forecast)}`).join(' ');return `<svg role="img" aria-label="Fluxo de receitas realizadas e previstas nos seis meses em exibição" viewBox="0 0 620 190" class="fin-chart"><line x1="42" y1="156" x2="590" y2="156" stroke="#d2c6ad"/><polyline points="${actual}" fill="none" stroke="#28576a" stroke-width="3"/><polyline points="${forecast}" fill="none" stroke="#ad873a" stroke-width="3" stroke-dasharray="6 4"/>${points.map((p,i)=>`<circle cx="${x(i)}" cy="${y(p.actual)}" r="4" fill="#28576a"/><circle cx="${x(i)}" cy="${y(p.forecast)}" r="4" fill="#ad873a"/><text x="${x(i)-18}" y="179" font-size="12" fill="#48433c">${esc(p.key.slice(5))}/${esc(p.key.slice(2,4))}</text>`).join('')}</svg><p class="muted">● Receitas liquidadas &nbsp; <span style="color:#ad873a">●</span> Recebíveis em aberto por vencimento. Pedidos comerciais aparecem em indicador separado.</p><div class="scroll"><table><tr><th>Mês</th><th>Recebido</th><th>Previsto</th><th>Pago</th></tr>${points.map(p=>`<tr><td>${esc(p.key)}</td><td>${money(p.actual)}</td><td>${money(p.forecast)}</td><td>${money(p.out)}</td></tr>`).join('')}</table></div>`}
function renderFinance360(sub){const{filters,month,matches}=financeScope(),ledger=s.officeFinance.filter(matches),open=ledger.filter(finOpen),incoming=open.filter(x=>x.Tipo==='Receita'),outgoing=open.filter(x=>x.Tipo==='Despesa'),realized=ledger.filter(x=>!finOpen(x)&&finDate(x).startsWith(month)),income=finSum(realized.filter(x=>x.Tipo==='Receita')),expense=finSum(realized.filter(x=>x.Tipo==='Despesa')),overdue=incoming.filter(x=>x.Vencimento&&x.Vencimento<today()),late=finSum(overdue),aging=[['A vencer',incoming.filter(x=>!x.Vencimento||x.Vencimento>=today())],['1–30 dias',incoming.filter(x=>agingDays(x.Vencimento)>=1&&agingDays(x.Vencimento)<=30)],['31–60 dias',incoming.filter(x=>agingDays(x.Vencimento)>=31&&agingDays(x.Vencimento)<=60)],['61+ dias',incoming.filter(x=>agingDays(x.Vencimento)>60)]],projection=financeProjection(),orders=s.orders.filter(x=>x.date?.startsWith(month)&&!['Cancelado','Orçamento'].includes(x.status)&&(!filters.brand||x.brand===filters.brand)&&(!filters.owner||x.user===filters.owner)&&(!filters.client||x.clientId===filters.client)),sales=orders.reduce((sum,x)=>sum+Number(x.amount||0),0),goals=s.goals.filter(x=>x.month===month&&!x.brand&&(!filters.owner||x.user===filters.owner)),goal=goals.reduce((sum,x)=>sum+Number(x.amount||0),0),won=s.opportunities.filter(x=>['Ganho','Pedido confirmado'].includes(x.stage)&&x.wonAt?.startsWith(month)&&x.createdAt&&matches(x)),cycles=won.map(x=>Math.max(0,(new Date(x.wonAt)-new Date(x.createdAt))/864e5)).filter(Number.isFinite),brands=[...new Set([...s.industries.map(x=>x.name),...s.orders.map(x=>x.brand),...ledger.map(x=>x['Marca/Indústria'])].filter(Boolean))].sort((a,b)=>a.localeCompare(b,'pt-BR')),owners=teamNames(),centers=[...new Set(ledger.map(x=>x['Centro de custo']).filter(Boolean))].sort(),people=s.clients.slice().sort((a,b)=>a.name.localeCompare(b.name,'pt-BR'));
 const sel=(label,name,options)=>`<label>${label}<select onchange="financeFilter('${name}',this.value)"><option value="">Todos</option>${options.map(([v,l])=>`<option value="${esc(v)}" ${filters[name]===v?'selected':''}>${esc(l)}</option>`).join('')}</select></label>`;
 const pay=rows=>rows.slice().sort((a,b)=>String(a.Vencimento||'9999').localeCompare(String(b.Vencimento||'9999'))).slice(0,12).map(x=>`<tr><td>${esc(x.Vencimento||'—')}</td><td>${esc(x.clientId?client(x.clientId).name:(x.Contraparte||x['Descrição']||'—'))}</td><td>${esc(x['Descrição']||'')}</td><td>${money(x.Valor)}</td><td><button type="button" onclick="editFinanceEntry('${esc(x.id)}')">Abrir</button> ${x.clientId?`<button type="button" class="secondary" onclick="openClient360('${esc(x.clientId)}')">Cliente</button>`:''}</td></tr>`).join('')||'<tr><td colspan="5">Nenhum registro.</td></tr>';
 return `<div class="page-heading"><div><span class="eyebrow">Gestão financeira · L2 ONE</span><h2>Visão geral</h2><p>Comissões da L2, vencimentos e vendas das indústrias em indicadores separados.</p></div><button type="button" onclick="window.financeSection='lancamentos';show('finance')">+ Novo lançamento</button></div>${sub}
 <div class="box fin-filters"><label>Período<input type="month" value="${esc(month)}" onchange="financeFilter('month',this.value)"></label>${sel('Indústria','brand',brands.map(x=>[x,x]))}${sel('Responsável','owner',owners.map(x=>[x,x]))}${sel('Cliente','client',people.map(x=>[x.id,x.name]))}${sel('Centro de custo','center',centers.map(x=>[x,x]))}${sel('Status','status',[['aberto','Em aberto'],['vencido','Vencido'],['liquidado','Liquidado']])}</div>
 <div class="cards fin-kpis"><div class="card">Receita recebida<strong>${money(income)}</strong><small>Liquidações no período</small></div><div class="card">A receber<strong>${money(finSum(incoming))}</strong><small>Contas registradas em aberto</small></div><div class="card">A pagar<strong>${money(finSum(outgoing))}</strong></div><div class="card">Saldo realizado<strong>${money(income-expense)}</strong><small>Entradas − saídas liquidadas</small></div><div class="card">Vendas registradas<strong>${money(sales)}</strong><small>${orders.length} pedidos das indústrias · ticket ${orders.length?money(sales/orders.length):'—'}</small></div><div class="card">Meta comercial<strong>${goal?money(goal):'Não definida'}</strong><small>${goal?(100*sales/goal).toFixed(1)+'% de atingimento':'Cadastre em Gestão'}</small></div><div class="card">Inadimplência<strong>${finSum(incoming)>0?(late/finSum(incoming)*100).toFixed(1)+'%':'—'}</strong><small>${money(late)} vencidos · contas registradas</small></div><div class="card">Ciclo médio de vendas<strong>${cycles.length?(cycles.reduce((a,b)=>a+b,0)/cycles.length).toFixed(1)+' dias':'Sem histórico'}</strong><small>Da criação ao ganho no CRM</small></div></div>
 <div class="fin-grid"><section class="box"><h3>Fluxo de caixa · realizado x projetado</h3>${financeChart(financeSeries(ledger,month))}</section><section class="box"><h3>Recebíveis por atraso</h3>${aging.map(([label,rows])=>`<p><b>${label}</b> · ${rows.length} · ${money(finSum(rows))}</p>`).join('')}<p class="muted">Atraso calculado sobre o vencimento; concilie com a indústria antes de cobrar.</p><h4>Previsão comercial do CRM</h4><p>${projection.length} negociações ganhas ainda sem faturamento conciliado.</p>${projection.slice(0,7).map(x=>`<p>${esc(client(x.clientId).name)} · ${esc(x.brand)} · comissão ${x.estimated===null?'percentual pendente':money(x.estimated)} <button type="button" onclick="bookCommissionForecast('${esc(x.id)}')">Conferir</button></p>`).join('')||'<p>Nenhuma previsão nesta seleção.</p>'}</section></div>
 <div class="box"><h3>Contas e movimentações</h3><p class="muted">Abra o registro para editar, liquidar ou consultar a origem. Valores financeiros não incluem automaticamente o total dos pedidos.</p><div class="scroll"><table><tr><th>Vencimento</th><th>Cliente / fornecedor</th><th>Descrição</th><th>Valor</th><th>Ação</th></tr>${pay(ledger.filter(x=>String(x.Vencimento||x.Data||'').slice(0,7)===month&&(!filters.status||(filters.status==='liquidado'&&!finOpen(x))||(filters.status==='aberto'&&finOpen(x))||(filters.status==='vencido'&&finOpen(x)&&x.Vencimento&&x.Vencimento<today()))))}</table></div><button type="button" class="secondary" onclick="window.financeSection='lancamentos';show('finance')">Ver todas as contas</button></div>
 <div class="box"><h3>Margem e aquisição por cliente</h3><p class="muted">Margem exige custos atribuídos; LTV e CAC exigem receita própria e custos de aquisição vinculados ao cliente. Exibiremos esses índices quando os vínculos estiverem completos, sem estimativas artificiais.</p></div>`}
function agingDays(due){if(!due||due>=today())return 0;return Math.ceil((new Date(today()+'T12:00:00')-new Date(due+'T12:00:00'))/864e5)}
function bookCommissionForecast(id){const item=s.opportunities.find(x=>x.id===id);if(!item)return;const rate=s.commissionRates.find(x=>x.id===commissionKey(item.brand))?.rate;if(rate===undefined)return alert('Cadastre o percentual de comissão da indústria na aba Gestão antes de registrar o recebível.');window.financeSection='lancamentos';show('finance');const form=$('quickFinanceForm');form.elements.Tipo.value='Receita';form.elements.namedItem('Grupo DRE').value='Receita operacional';form.elements.Data.value=today();form.elements.namedItem('Competência').value=(item.closeDate||today()).slice(0,7);form.elements.Vencimento.value=item.closeDate||'';form.elements.Categoria.value='Comissão prevista';form.elements.namedItem('Descrição').value='Previsão de comissão · '+item.brand;form.elements.namedItem('Marca/Indústria').value=item.brand;form.elements.namedItem('Contraparte').value=item.brand;form.elements.clientId.value=item.clientId;form.elements.sourceOpportunityId.value=item.id;form.elements.Valor.value=formatBRLInput(Math.round(finCents(item.amount)*Number(rate)/100)/100);form.scrollIntoView({behavior:'smooth'});alert('Confira o valor, a competência e o vencimento antes de salvar. O pedido não é receita da L2.');}
