/* Strategic tools live inside existing screens; no additional navigation. */
window.L2Strategy=(()=>{
const notice=()=>document.getElementById('strategyNotice');
async function request(path,data,method='POST'){
 if(!s.token)throw Error('Entre no sistema para usar esta ação.');
 if(s.pending.length)throw Error('Sincronize os registros pendentes antes de executar esta ação.');
 const r=await fetch(s.server+'/api/strategy'+path,{method,headers:{Authorization:'Bearer '+s.token,'Content-Type':'application/json'},...(data===undefined?{}:{body:JSON.stringify(data)})});
 const body=await r.json();if(!r.ok)throw Error(typeof body.detail==='string'?body.detail:'Revise os campos informados.');return body;
}
const field=(name,label,type='text',extra='')=>`<label>${label}<input name="${name}" type="${type}" ${extra}></label>`;
function panel(tab){
 if(!s.token||!hasSector('commercial'))return '';
 const action='<p id="strategyNotice" role="status" aria-live="polite"></p>';
 if(tab==='clientes')return `<details class="box"><summary>Encontrar clientes · TDC</summary><p class="muted">Qualifique empresas do PA/AP com demanda comprovada. CNPJ, canal, porte e potencial geram a pontuação; qualificados entram na carteira sem duplicação.</p><form onsubmit="L2Strategy.discover(event)"><div class="row"><label>UF de busca<select name="state"><option value="">PA e AP</option><option>PA</option><option>AP</option></select></label>${field('segment','Demanda por segmento')}${field('urgency','Urgência até (dias)','number','value="30" min="0" max="90"')}</div><button class="secondary">Buscar leads qualificados</button></form><div id="strategyLeads"></div><form onsubmit="L2Strategy.qualify(event)"><div class="row">${field('taxId','CNPJ','text','required minlength="14" maxlength="18"')}<button type="button" class="secondary" onclick="L2Strategy.lookup(this.form)">Consultar empresa</button>${field('name','Razão social','text','required minlength="2" maxlength="180"')}<label>UF<select name="state"><option>PA</option><option>AP</option></select></label>${field('city','Cidade','text','required minlength="2"')}<label>Canal<select name="channel">${['Farma','Alimentar','Cosméticos','Especializada','Departamento','Salão','Atacado'].map(x=>`<option>${x}</option>`).join('')}</select></label>${field('cnae','CNAE (7 dígitos)','text','required pattern="[0-9]{7}"')}<label>Porte<select name="size">${['MEI','Micro','Pequena','Média','Grande'].map(x=>`<option>${x}</option>`).join('')}</select></label>${field('segment','Produtos ou segmento procurado','text','required minlength="2" maxlength="120"')}${field('estimatedMonthlyValue','Potencial mensal (R$)','number','required min="0" step="0.01"')}${field('urgencyDays','Compra prevista em (dias)','number','required min="0" max="90"')}${field('evidenceDate','Data da evidência','date',`required value="${today()}"`)}${field('phone','Telefone com DDD')}${field('address','Endereço')}${field('district','Bairro')}${field('latitude','Latitude','number','step="any" min="-90" max="90"')}${field('longitude','Longitude','number','step="any" min="-180" max="180"')}${field('opens','Abre às','time','required value="09:00"')}${field('closes','Fecha às','time','required value="18:00"')}</div><label>Evidência da necessidade<textarea name="demandEvidence" required minlength="10" maxlength="1000" placeholder="Ex.: comprador solicitou reposição de maquiagem em contato de hoje."></textarea></label><button>Qualificar e incluir</button></form>${action}</details>`;
 if(tab==='rota'&&hasSector('routes'))return `<details class="box"><summary>Planejar visitas · SRI</summary><p class="muted">Prioriza TDC e MCR e respeita horários. Distâncias e tempo são estimativas geográficas; confirme travessias e estradas antes da saída. Clientes sem coordenadas aparecerão como pendência.</p><details><summary>Coordenadas e horários do cliente</summary><form onsubmit="L2Strategy.location(event)"><div class="row"><label>Cliente<select name="clientId" required><option value="">Selecione</option>${s.clients.map(c=>`<option value="${esc(c.id)}">${esc(c.name)}</option>`).join('')}</select></label>${field('latitude','Latitude','number','required step="any" min="-90" max="90"')}${field('longitude','Longitude','number','required step="any" min="-180" max="180"')}${field('opens','Abre às','time','required value="09:00"')}${field('closes','Fecha às','time','required value="18:00"')}<label>Fechamento semanal<select name="closedDays"><option value="6">Domingo</option><option value="5,6">Sábado e domingo</option><option value="">Abre todos os dias</option></select></label></div><button class="secondary">Salvar localização</button></form></details><form onsubmit="L2Strategy.route(event)"><div class="row">${field('date','Data','date',`required value="${today()}"`)}<label>UF<select name="state"><option>PA</option><option>AP</option></select></label>${field('city','Cidade','text','required minlength="2"')}${field('originLatitude','Latitude da saída','number','required step="any" min="-90" max="90"')}${field('originLongitude','Longitude da saída','number','required step="any" min="-180" max="180"')}${field('start','Início','time','required value="09:00"')}${field('end','Retorno até','time','required value="18:00"')}${field('limit','Atendimentos','number','required min="1" max="10" value="8"')}${field('visitMinutes','Minutos por visita','number','required min="15" max="120" value="40"')}${field('costPerKm','Custo por km (R$)','number','required min="0" step="0.01" value="0"')}</div><button name="action" value="preview">Conferir sugestão</button> <button class="secondary" name="action" value="commit">Criar na minha agenda</button></form><div id="strategyRouteResult" role="status"></div>${action}</details>`;
 if(['hoje','crm','crescimento'].includes(tab))return `<details class="box"><summary>Acompanhamento e reativação · MCR</summary><p class="muted">Contato semanal · em risco a partir de 15 dias · inativo a partir de 60 dias. Sem compras registradas: sem histórico. A frequência de recompra é calculada quando há pelo menos três datas de compra.</p><button type="button" class="secondary" onclick="L2Strategy.overview()">Consultar prioridades</button> <button type="button" class="secondary" onclick="L2Strategy.refresh()">Atualizar lembretes</button><div id="strategyOverview"></div><form id="strategyConsentForm" onsubmit="L2Strategy.consent(event)"><div class="row"><label>Cliente<select name="clientId" required><option value="">Selecione</option>${s.clients.map(c=>`<option value="${esc(c.id)}">${esc(c.name)}</option>`).join('')}</select></label><label>WhatsApp<select name="enabled"><option value="true">Autoriza contato</option><option value="false">Suspender contato</option></select></label>${field('evidence','Registro da autorização ou suspensão','text','required minlength="5" maxlength="500"')}</div><button class="secondary">Registrar preferência</button> <button type="button" class="secondary" onclick="L2Strategy.history(this.form)">Histórico de envios</button></form><div id="strategySendHistory"></div>${['Ana Paula','Euler'].includes(s.user)?`<form id="strategySettingsForm" onsubmit="L2Strategy.settings(event)"><div class="row"><label>Cadência automática<select name="enabled"><option value="false">Desativada</option><option value="true">Ativada</option></select></label>${field('template','Modelo aprovado na Meta','text','pattern="[a-z0-9_]*" maxlength="100"')}${field('language','Idioma','text','required value="pt_BR"')}</div><p class="muted">Modelo com duas variáveis no corpo: nome do cliente e segmento. Disparos em dias úteis, das 9h às 18h, para contatos autorizados.</p><button class="secondary">Salvar cadência</button> <button type="button" class="secondary" onclick="L2Strategy.readSettings()">Consultar configuração atual</button></form>`:''}${action}</details>`;
 return '';
}
function message(text){if(notice())notice().textContent=text;}
async function run(action){try{message('Processando…');await action();}catch(e){message(e.message);}}
async function qualify(e){e.preventDefault();const f=e.target,d=Object.fromEntries(new FormData(f));for(const k of ['urgencyDays','estimatedMonthlyValue','latitude','longitude'])d[k]=d[k]===''?null:Number(d[k]);await run(async()=>{const r=await request('/tdc/qualify',d);await sync(true);message(r.qualification.tag+' · Pontuação '+r.qualification.score+(r.clientId?' · Incluído na carteira':' · Lead aguardando revisão'));});}
async function lookup(f){await run(async()=>{const r=await fetch(s.server+'/api/clients/lookup-cnpj',{method:'POST',headers:{Authorization:'Bearer '+s.token,'Content-Type':'application/json'},body:JSON.stringify({cnpj:f.elements.taxId.value})});const d=await r.json();if(!r.ok)throw Error(d.detail||'Consulta indisponível');for(const k of ['name','state','city','phone','address','district','cnae'])if(d.client[k]&&f.elements[k])f.elements[k].value=d.client[k];message('Dados consultados. Confira CNAE, porte e a necessidade antes de qualificar.');});}
async function route(e){e.preventDefault();const d=Object.fromEntries(new FormData(e.target));for(const k of ['originLatitude','originLongitude','limit','visitMinutes','costPerKm'])d[k]=Number(d[k]);d.commit=e.submitter?.value==='commit';await run(async()=>{const r=await request('/sri/plan',d);const el=document.getElementById('strategyRouteResult');if(el)el.innerHTML=`<p>${r.stops.length} visitas · ${r.distanceKm} km estimados · despesa prevista ${money(r.estimatedExpense)}</p><ol>${r.stops.map(x=>`<li>${esc(client(x.clientId)?.name||x.clientId)} · ${esc(x.arrival)}–${esc(x.departure)} · ${esc(x.reason)}</li>`).join('')}</ol><p>${r.omitted.length} clientes fora da sugestão.</p><ul>${r.omitted.map(x=>`<li>${esc(client(x.clientId)?.name||x.clientId)} · ${esc(x.reason)}</li>`).join('')}</ul>`;if(d.commit)await sync(true);message(d.commit?'Visitas e conferência de despesas registradas na agenda.':'Sugestão pronta para conferir.');});}
async function overview(){await run(async()=>{const r=await request('/overview',undefined,'GET');const el=document.getElementById('strategyOverview');if(el)el.innerHTML=`<div class="scroll"><table><thead><tr><th>Cliente</th><th>Situação</th><th>Próximo contato</th><th>Ciclo</th><th>Ação</th></tr></thead><tbody>${r.clients.slice(0,100).map(c=>`<tr><td>${esc(c.name)}</td><td>${esc(c.mcr.status)}</td><td>${esc(c.mcr.nextContact)}</td><td>${c.mcr.cycleDays} dias · ${esc(c.mcr.cycleSource)}</td><td><button class="secondary" data-strategy-client="${esc(c.id)}">Acompanhar</button></td></tr>`).join('')}</tbody></table></div><p>Buscar demanda nos segmentos: ${esc(r.searchSuggestions.join(', ')||'Nenhuma sugestão derivada de clientes inativos.')}</p>`;el?.querySelectorAll('[data-strategy-client]').forEach(b=>b.onclick=()=>openClient360(b.dataset.strategyClient));message('Prioridades atualizadas.');});}
async function refresh(){await run(async()=>{const r=await request('/mcr/refresh',{});await sync(true);message(r.updated+' clientes atualizados.');});}
async function settings(e){e.preventDefault();const d=Object.fromEntries(new FormData(e.target));d.enabled=d.enabled==='true';await run(async()=>{await request('/mcr/settings',d,'PUT');message('Configuração da cadência salva.');});}
async function consent(e){e.preventDefault();const d=Object.fromEntries(new FormData(e.target));await run(async()=>{await request('/mcr/consent/'+encodeURIComponent(d.clientId),{enabled:d.enabled==='true',evidence:d.evidence},'PUT');await sync(true);message('Preferência de contato registrada.');});}
async function discover(e){e.preventDefault();const d=new URLSearchParams(new FormData(e.target));await run(async()=>{const r=await request('/tdc/discover?'+d,undefined,'GET');const el=document.getElementById('strategyLeads');if(el)el.innerHTML='<ul>'+r.leads.map(l=>`<li>${esc(l.name)} · ${esc(l.city)} / ${esc(l.state)} · ${esc(l.tdc.segment)} · ${l.tdc.score} pontos · ${l.evidenceExpired?'Renovar evidência':esc(l.status)}</li>`).join('')+'</ul>';message(r.leads.length+' leads encontrados na base L2.');});}
async function location(e){e.preventDefault();const d=Object.fromEntries(new FormData(e.target)),id=d.clientId;delete d.clientId;d.latitude=Number(d.latitude);d.longitude=Number(d.longitude);d.closedDays=d.closedDays?d.closedDays.split(',').map(Number):[];await run(async()=>{await request('/sri/location/'+encodeURIComponent(id),d,'PUT');await sync(true);message('Localização e horários salvos.');});}
async function readSettings(){await run(async()=>{const r=await request('/mcr/settings',undefined,'GET'),f=document.getElementById('strategySettingsForm');if(f){f.elements.enabled.value=String(r.enabled);f.elements.template.value=r.template;f.elements.language.value=r.language;}message('Configuração atual consultada.');});}
async function history(f){const id=f.elements.clientId.value;if(!id)return message('Selecione um cliente.');await run(async()=>{const r=await request('/mcr/history?client_id='+encodeURIComponent(id),undefined,'GET'),el=document.getElementById('strategySendHistory');if(el)el.innerHTML='<ul>'+r.messages.map(m=>`<li>${esc(m.attemptAt)} · ${esc(m.status)} · ${esc(m.deliveryStatus||'Sem confirmação de entrega')}</li>`).join('')+'</ul>';message(r.messages.length+' tentativas registradas.');});}
function badge(c){return c.tdc?'<small class="uf-badge">'+esc(c.tdc.tag)+' · '+Number(c.tdc.score)+' pontos</small>':'';}
return {panel,qualify,lookup,route,overview,refresh,settings,consent,discover,location,history,readSettings,badge};
})();
