const fs=require('fs'),vm=require('vm'),assert=require('assert');
const app=fs.readFileSync('app.js','utf8'),start=app.indexOf('function crm360Facts(data)'),end=app.indexOf('function crm360Panel()',start);
const ctx={CRMOperations:{attendedVisit:v=>v.result==='Visitado - pedido'},orderBrandTotals:o=>new Map((o.items||[]).map(i=>[i.brand,Math.round(Number(i.subtotal)*100)])),Map,Set,Date};vm.createContext(ctx);vm.runInContext(app.slice(start,end),ctx);
const state={clients:[{id:'a',name:'A'},{id:'b',name:'B'}],orders:[{id:'one',clientId:'a',status:'Confirmado',amount:100,user:'Euler',items:[{brand:'BT',subtotal:60},{brand:'BM',subtotal:40}]},{id:'two',clientId:'a',status:'Faturado',amount:50,user:'Erika',items:[{brand:'BT',subtotal:50}]},{id:'three',clientId:'b',status:'Pendente',amount:10,user:'Euler'},{id:'quote',clientId:'b',status:'Orçamento',proposalSentAt:'2026-10-07T12:00:00Z',amount:20,user:'Erika'},{id:'cancel',status:'Cancelado'}],opportunities:[{id:'opp',clientId:'a',stage:'Ganho',orderId:'one',owner:'Euler',stageHistory:[{stage:'Proposta enviada'}]},{id:'neg',clientId:'b',stage:'Negociação',owner:'Erika',amount:80}],fulfillments:[{id:'f',orderId:'one',stage:'Entregue',at:'2026-10-07T12:00:00Z'}],routes:[{id:'r1',clientId:'a',date:'2026-10-06',user:'Euler'},{id:'r2',clientId:'b',date:'2026-10-08',user:'Euler'}],visits:[{clientId:'a',date:'2026-10-06',user:'Euler',result:'Visitado - pedido'}]};
const f=ctx.crm360Facts(state);assert.equal(f.orders.length,4);assert.equal(f.confirmed.length,2);assert.equal(f.billed.length,2);assert.equal(f.delivered.length,1);assert.equal(f.visits.length,1);assert.equal(f.postSale[0].due,'2026-10-14');assert.equal(f.rows.filter(x=>x.stage==='Ganho').length,0);assert.equal(f.rows.filter(x=>x.stage==='Pedido pendente').length,1);assert.equal(f.rows.filter(x=>x.stage==='Proposta enviada').length,1);assert.equal(f.industries.find(x=>x.brand==='BT').ids.size,2);assert.equal(f.industries.find(x=>x.brand==='BT').cents,11000);assert.equal(f.sellers.find(x=>x.owner==='Euler').converted,1);assert.equal(f.sellers.find(x=>x.owner==='Erika').negotiations,1);
state.fulfillments[0].stage='Pós-venda concluído';state.fulfillments[0].postSaleResult='Cliente satisfeito';assert(ctx.crm360Facts(state).postSale[0].completed);
state.orders[0].status='Confirmado';state.fulfillments=[];state.billedOrderIds=['one'];assert.equal(ctx.crm360Facts(state).billed.length,2);
// Changing opportunity stage moves the current count, not a duplicate row.
state.opportunities[1].stage='Proposta enviada';assert.equal(ctx.crm360Facts(state).rows.filter(x=>x.stage==='Proposta enviada').length,2);
console.log('CRM equipe: pedidos únicos, conversão, visitas, multimarcas, faturamento, pós-venda: OK');

state.orders.find(x=>x.id==='quote').proposalSentAt='';assert.equal(ctx.crm360Facts(state).rows.filter(x=>x.stage==='Orçamento em elaboração').length,1);

state.orders[0].status='Confirmado';state.fulfillments=[];state.billedDocuments=[{orderId:'one',brand:'BT',billed:30}];state.billedOrderIds=['one'];const partial=ctx.crm360Facts(state);assert(!partial.industries.some(x=>x.brand==='BM'));assert.equal(partial.industries.find(x=>x.brand==='BT').invoiceCents,3000);
