const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const source=fs.readFileSync(__dirname+'/../app.js','utf8');
function fragment(begin,end){const a=source.indexOf(begin),b=source.indexOf(end,a);assert(a>=0&&b>a);return source.slice(a,b)}
let sequence=0;
const old={type:'order',changeId:'old',data:{id:'o1',amount:120,items:[{sku:'A',quantity:2}]}};
const state={pending:[old,{type:'order',changeId:'newer',data:{id:'o1',sellerResponsible:'Erika',status:'Confirmado'}},{type:'order',changeId:'other',data:{id:'o2'}},{type:'client',changeId:'client',data:{id:'o1'}}],orders:[{id:'o1'}],sellers:['Erika','Euler']};
const ctx={s:state,uid:()=> 'repair-'+(++sequence),esc:x=>String(x??'').replaceAll('"','&quot;'),client:()=>({name:'Loja'}),sellerOptions:()=>'<option>Erika</option>',administrativeOrderEntry:()=>true,queue:()=>{},show:()=>{},save:()=>{},sync:()=>{},alert:()=>{throw Error('unexpected alert')},FormData:class{get(){return 'Erika'}}};
vm.createContext(ctx);
vm.runInContext(fragment('function repairQueuedOrderSeller(','function pendingClientRegistrationIssues(')+fragment('function assignOrderSeller(','function teamNames('),ctx);
assert.equal(ctx.pendingOrderSellerIssues().length,2);
assert.match(ctx.pendingOrderRepairsHTML(),/pendingOrderRepairs/);
const inFlight=JSON.parse(JSON.stringify(state.pending[0]));
ctx.assignOrderSeller('o1','Erika');
assert.equal(inFlight.data.sellerResponsible,undefined);
assert.equal(inFlight.changeId,'old');
assert.equal(state.pending[0].data.sellerResponsible,'Erika');
assert.equal(state.pending[0].data.amount,120);
assert.equal(state.pending[0].data.items[0].quantity,2);
assert.equal(state.pending[1].data.status,'Confirmado');
assert.notEqual(state.pending[0].changeId,inFlight.changeId);
assert.equal(state.pending[2].changeId,'other');
assert.equal(state.pending[3].changeId,'client');
assert.equal(ctx.pendingOrderSellerIssues().length,1);
ctx.repairPendingOrderSeller({preventDefault(){},target:{}},'o2');
assert.equal(ctx.pendingOrderSellerIssues().length,0);
assert(state.pending.every(x=>x.type!=='order'||x.data.commissionSeller==='Erika'));
console.log('Reparo de fila, isolamento de pedidos e resposta em voo: OK');
